export const HASHTAG_SEARCH_REQUEST = "HASHTAG_SEARCH_REQUEST";
export const HASHTAG_SEARCH_SUCCESS = "HASHTAG_SEARCH_SUCCESS";
export const HASHTAG_SEARCH_FAIL = "HASHTAG_SEARCH_FAIL";
export const HASHTAG_SEARCH_CLEAR = "HASHTAG_SEARCH_CLEAR";
